In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set()
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('original.csv')
data

SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [3]:
data

SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [4]:
y = data['GPA']
x = data[['SAT','Rand 1,2,3']]

In [5]:
reg = LinearRegression()

In [6]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
reg.score(x,y)

0.40668119528142815

In [8]:
reg.intercept_

0.29603261264909353

In [9]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [10]:
r_sq = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

###Calculating Adjusted R-squared


$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

n=84(number of observations),
p=2(the number of predictors)

In [11]:
Adjr_sq = 1 - (1 - r_sq) * ((n-1)/(n-p-1))
Adjr_sq

0.39203134825134

In [12]:
r_sq

0.40668119528142815

In [13]:
###Feature Selection
from sklearn.feature_selection import f_regression

In [14]:
f_regression(x,y) #First array contains F-Statistic and Second Array contains P-values
#These P-values don't consider relationship between variables.They are p-values obtained throught seperate simple linear regression(In this case it is actually the p-value of the f-statistic.Since they are same compared to the p-value of the independent variable)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [15]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [16]:
p_values.round(3)

array([0.   , 0.676])

In [17]:
###Create a summary table
reg_summary = pd.DataFrame(data=x.columns.values,columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [18]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['R-Squared'] = reg.score(x,y)
reg_summary['Adjusted R-Squared'] = Adjr_sq
reg_summary['P-Values'] = p_values.round(3)
reg_summary
#p-values are one of the best ways to determine if a variable is redundant,but they provide no information whatsoever on HOW USEFUL a variable is

Features  Coefficients  R-Squared  Adjusted R-Squared  P-Values
0         SAT      0.001654   0.406681            0.392031     0.000
1  Rand 1,2,3     -0.008270   0.406681            0.392031     0.676

----Standardization----
#StandardScaler is a preprocessing module used to standardize (or scale) data

In [19]:
from sklearn.preprocessing import StandardScaler
data
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [20]:
scaler = StandardScaler()
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [21]:
#StandardScaler.transform(x) transforms the unscaled inputs using the information contained in the scaler object(feature-wise)
x_scaled = scaler.transform(x)
#When we get new data we will apply the scaling as we just did.
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [22]:
#Having features with same magnitude allows us to compare their actual magnitude
reg2 = LinearRegression()
reg2.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
reg2.coef_

array([ 0.17181389, -0.00703007])

In [24]:
reg_summary

Features  Coefficients  R-Squared  Adjusted R-Squared  P-Values
0         SAT      0.001654   0.406681            0.392031     0.000
1  Rand 1,2,3     -0.008270   0.406681            0.392031     0.676

In [25]:
reg2_summary = pd.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg2_summary['Weights'] = reg2.intercept_,reg2.coef_[0],reg2.coef_[1]

In [26]:
reg2_summary
#Weights is the machine learning word for coefficients
#The Intercept can be called bias
#The closer the weight is to 0, the smaller the impact
#When we perform Feature Scaling we don't care of a useless variable is there or not, since it is 0, anything multiplied by zero is zero
#SkLearn does not naively support p-values since ML-Practitioners apply some kind of feature scaling before fitting the model, we don't need to identify the worst performing features,they are automatically penalised for having a very small weight
#In general we prefer to leave out the worst performing features as they interact with the useful features and may bias the weight even if it is by a small amount

Features   Weights
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [27]:
#Making Predictions with standardized weights
new_data = pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [28]:
reg2.predict(new_data)

array([295.39979563, 312.58821497])

In [29]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [30]:
reg2.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [31]:
x3 = data['SAT']
x3 = x3.values.reshape(-1,1)
scaler2 = StandardScaler()
scaler2.fit(x3)
x3_scaled = scaler2.transform(x3)
reg3 = LinearRegression()
reg3 = reg3.fit(x3_scaled,y)

In [32]:
#What would happen if we did not include the Rand 1,2,3 ? Results should not change right?
new_data2 = pd.DataFrame(data=[1700,1800],columns=['SAT'])
new_data2

SAT
0  1700
1  1800

In [33]:
new_data2_scaled = scaler2.transform(new_data2)
new_data2_scaled
reg3.predict(new_data2_scaled)
#Actually i created a new scaler for this which was not required, we could just take the first column of the scaled x and create a new regression model
#Either way the results are the same , and if we round the predictions to 2 decimal places we find that the predictions are the same, which is why the developers left out p-values since it is not required if we perform Feature Scaling.

array([3.08970998, 3.25527879])